config/routes.rb
Rails.application.routes.draw do

  get '/team', to: "my_gossip#team"
  get '/contact', to: "my_gossip#contact"

  get '/index', to: "my_gossip#index"
  post '/index', to: "my_gossip#index_post", as: 'welcome_name'
  get '/welcome/:first_name', to: "my_gossip#welcome"

  get 'gossip/:id', to: "my_gossip#sh_gossips", as: 'my_gossip_gossip_id'

  get 'info/:author', to: "my_gossip#sh_author", as: 'my_gossip_gossip_author'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gosssip.rb
class Gosssip < ApplicationRecord
  belongs_to :user

  def self.show_gossip
    @array_gossip = Gosssip.all
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gosssips

  def self.show_user
    @array_user = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/my_gossip_controller.rb
class MyGossipController < ApplicationController

  def team
  end

  def contact
  end

  def index

  end

  def sh_gossips
    @user = params[:first_name]
    @array_user = User.all
    @array_gossip = Gosssip.all
  end

  def sh_author
    @user = params[:first_name]
    @array_user = User.all
    @array_gossip = Gosssip.all
  end

  def welcome
    @user = params[:first_name]
    @array_user = User.all
    @array_gossip = Gosssip.all
  end

  def index_post
    redirect_to "/welcome/#{params[:first_name]}"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_gossip_helper.rb
module MyGossipHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProjectV2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

     <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  </head>

  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/index">My Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/team">Team</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact">Contact</a>
      </li>
    </ul>
  </div>
</nav>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/my_gossip/contact.html.erb
<center>
  <br/><br/>
    <h1>Contacter la Team</h1>
</center>

app/views/my_gossip/index.html.erb
<center>
  <br/><br/>
  <h1>Bienvenue, connecte toi si tu veux voir les Gossips</h1>
    <form action='/index' method="POST">
      Saisi ici ton prénom :<br/>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="text" name="first_name"/><br/><br/>
      <input type="submit" name="Envoyer"/>
    </form>
</center>

app/views/my_gossip/sh_author.html.erb
<div class='container'>
  <center><h1>Page de présentation de <%=@array_user[params['author'].to_i].first_name %></h1>
  <br>
    <div>
      <p>
        <u>Prénom</u>: <%= @array_user[params['author'].to_i].first_name %><br>
        <u>Nom</u>: #Pas encore d'infos<br>
        <u>Age</u>: #Pas encore d'infos<br>
        <u>Email</u>: #Pas encore d'infos<br>
      </p>
    </div>

  <p>
    <%= link_to "Retour à la page du gossip", :back%>
  </p>
  </center>
</div>

app/views/my_gossip/sh_gossips.html.erb
<center>
<br>
<h1>Page du Gossip de <%="#{@array_gossip[params['id'].to_i].user.first_name}"%></h1>
<br>

<p>
  <u>Écrit par</u>: <%= link_to "#{@array_gossip[params['id'].to_i].user.first_name}", my_gossip_gossip_author_path((@array_gossip[params['id'].to_i].user.id)-1) %><br>
  <u>Titre du gossip</u>: <%= @array_gossip[params['id'].to_i].title %><br>
    <u>Gossip</u>: <%= @array_gossip[params['id'].to_i].content %><br>
    <u>Date de création</u>: <%= @array_gossip[params['id'].to_i].created_at %><br>

</p>

<p>
  <%= link_to "Retour à la page des gossips", welcome_name_path %>
</p>
</center>

app/views/my_gossip/team.html.erb
<center>
  <br/><br/>
    <h1>Jérémy Delmas</h1>
    <br/><br/>
    <h1>Athénaïs Dupuy</h1>
</center>

app/views/my_gossip/welcome.html.erb
<center>
  <br/><br/>
  <h2>BIENVENUE <%= @user %>  ! Ici c'est notre super site de potins, il est chouette, non ? </h2>
  <% x = 0 %>
  <div class="card-columns mx-2">
    <%while x < 12%>
    <div class="card border-primary mb-2 bg-light">
      <div class="card-body">
        <h5 class="card-title">  <%= @array_gossip[x].user.first_name %></h5>
        <h4 class="card-text">    <%= link_to "#{@array_gossip[x].title}", my_gossip_gossip_id_path(x) %></h4>
      </div>
    </div>
    <% x += 1 %>
    <% end %>
  </div>
</center>